// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Lnq_fjyYG7Q76zlQftuIcrPJnK5PU1M',
    appId: '1:651370591583:web:49055863fb65508716b2ea',
    messagingSenderId: '651370591583',
    projectId: 'posmar-8a5e9',
    authDomain: 'posmar-8a5e9.firebaseapp.com',
    storageBucket: 'posmar-8a5e9.firebasestorage.app',
    measurementId: 'G-2FPE8RXZ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKldaKOTC_fX0_55qk_FNqzqDlb-lrzk',
    appId: '1:651370591583:android:9ace4478a29c065316b2ea',
    messagingSenderId: '651370591583',
    projectId: 'posmar-8a5e9',
    storageBucket: 'posmar-8a5e9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Lnq_fjyYG7Q76zlQftuIcrPJnK5PU1M',
    appId: '1:651370591583:web:b6fc57e00f2d921716b2ea',
    messagingSenderId: '651370591583',
    projectId: 'posmar-8a5e9',
    authDomain: 'posmar-8a5e9.firebaseapp.com',
    storageBucket: 'posmar-8a5e9.firebasestorage.app',
    measurementId: 'G-ZYFQD8HLXQ',
  );
}
